/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cleanPet.telas;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author marcioc
 */
public class TelaAgenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAgenda
     */
    int anoFixo = 0, mesFixo = 0, diaFixo;
    int anoAltera = 0, mesAltera = 0, diaAltera = 0;
    int valorSelecao = 0;

    public TelaAgenda() {
        initComponents();
        iniciaCalendario();
        diaCalendario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        cboSelAno = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        lblDom = new javax.swing.JLabel();
        lblSeg = new javax.swing.JLabel();
        lblTer = new javax.swing.JLabel();
        lblQua = new javax.swing.JLabel();
        lblQui = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblSab = new javax.swing.JLabel();
        lblD1 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        lblD3 = new javax.swing.JLabel();
        lblD4 = new javax.swing.JLabel();
        lblD5 = new javax.swing.JLabel();
        lblD6 = new javax.swing.JLabel();
        lblD7 = new javax.swing.JLabel();
        lblD8 = new javax.swing.JLabel();
        lblD9 = new javax.swing.JLabel();
        lblD10 = new javax.swing.JLabel();
        lblD11 = new javax.swing.JLabel();
        lblD12 = new javax.swing.JLabel();
        lblD13 = new javax.swing.JLabel();
        lblD14 = new javax.swing.JLabel();
        lblD15 = new javax.swing.JLabel();
        lblD16 = new javax.swing.JLabel();
        lblD17 = new javax.swing.JLabel();
        lblD18 = new javax.swing.JLabel();
        lblD19 = new javax.swing.JLabel();
        lblD20 = new javax.swing.JLabel();
        lblD21 = new javax.swing.JLabel();
        lblD22 = new javax.swing.JLabel();
        lblD23 = new javax.swing.JLabel();
        lblD24 = new javax.swing.JLabel();
        lblD25 = new javax.swing.JLabel();
        lblD26 = new javax.swing.JLabel();
        lblD27 = new javax.swing.JLabel();
        lblD28 = new javax.swing.JLabel();
        lblD29 = new javax.swing.JLabel();
        lblD30 = new javax.swing.JLabel();
        lblD31 = new javax.swing.JLabel();
        lblD32 = new javax.swing.JLabel();
        lblD33 = new javax.swing.JLabel();
        lblD34 = new javax.swing.JLabel();
        lblD35 = new javax.swing.JLabel();
        lblD36 = new javax.swing.JLabel();
        lblD37 = new javax.swing.JLabel();
        lblD38 = new javax.swing.JLabel();
        lblD39 = new javax.swing.JLabel();
        lblD40 = new javax.swing.JLabel();
        lblD41 = new javax.swing.JLabel();
        lblD42 = new javax.swing.JLabel();
        cboSelMes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agenda");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cboSelAno.setEditable(true);

        lblDom.setForeground(new java.awt.Color(255, 0, 0));
        lblDom.setText("Dom");

        lblSeg.setText("Seg");

        lblTer.setText("Ter");

        lblQua.setText("Qua");

        lblQui.setText("Qui");

        lblSex.setText("Sex");

        lblSab.setText("Sab");

        lblD1.setForeground(new java.awt.Color(255, 0, 0));
        lblD1.setText("0");

        lblD2.setText("0");

        lblD3.setText("0");

        lblD4.setText("0");

        lblD5.setText("0");

        lblD6.setText("0");

        lblD7.setText("0");

        lblD8.setForeground(new java.awt.Color(255, 0, 0));
        lblD8.setText("0");

        lblD9.setText("0");

        lblD10.setText("0");

        lblD11.setText("0");

        lblD12.setText("0");

        lblD13.setText("0");

        lblD14.setText("0");

        lblD15.setForeground(new java.awt.Color(255, 0, 0));
        lblD15.setText("0");

        lblD16.setText("0");

        lblD17.setText("0");

        lblD18.setText("0");

        lblD19.setText("0");

        lblD20.setText("0");

        lblD21.setText("0");

        lblD22.setForeground(new java.awt.Color(255, 0, 0));
        lblD22.setText("0");

        lblD23.setText("0");

        lblD24.setText("0");

        lblD25.setText("0");

        lblD26.setText("0");

        lblD27.setText("0");

        lblD28.setText("0");

        lblD29.setForeground(new java.awt.Color(255, 0, 0));
        lblD29.setText("0");

        lblD30.setText("0");

        lblD31.setText("0");

        lblD32.setText("0");

        lblD33.setText("0");

        lblD34.setText("0");

        lblD35.setText("0");

        lblD36.setForeground(new java.awt.Color(255, 0, 0));
        lblD36.setText("0");

        lblD37.setText("0");

        lblD38.setText("0");

        lblD39.setText("0");

        lblD40.setText("0");

        lblD41.setText("0");

        lblD42.setText("0");

        cboSelMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", " ", " ", " " }));

        jLayeredPane2.setLayer(cboSelAno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblDom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblSeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblTer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblQua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblQui, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblSex, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblSab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(cboSelMes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblDom)
                            .addComponent(lblD1)
                            .addComponent(lblD8)
                            .addComponent(lblD15)
                            .addComponent(lblD22)
                            .addComponent(lblD29)
                            .addComponent(lblD36))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSeg)
                            .addComponent(lblD2)
                            .addComponent(lblD9)
                            .addComponent(lblD16)
                            .addComponent(lblD23)
                            .addComponent(lblD30)
                            .addComponent(lblD37))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(lblD3)
                                .addComponent(lblD10)
                                .addComponent(lblD17)
                                .addComponent(lblD24)
                                .addComponent(lblD31)
                                .addComponent(lblD38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(lblTer)
                                .addGap(18, 18, 18)))
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblQua)
                            .addComponent(lblD4)
                            .addComponent(lblD11)
                            .addComponent(lblD18)
                            .addComponent(lblD25)
                            .addComponent(lblD32)
                            .addComponent(lblD39))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblQui)
                            .addComponent(lblD5)
                            .addComponent(lblD12)
                            .addComponent(lblD19)
                            .addComponent(lblD26)
                            .addComponent(lblD33)
                            .addComponent(lblD40))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSex)
                            .addComponent(lblD6)
                            .addComponent(lblD13)
                            .addComponent(lblD20)
                            .addComponent(lblD27)
                            .addComponent(lblD34)
                            .addComponent(lblD41))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSab)
                            .addComponent(lblD7)
                            .addComponent(lblD14)
                            .addComponent(lblD21)
                            .addComponent(lblD28)
                            .addComponent(lblD35)
                            .addComponent(lblD42)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cboSelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cboSelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSelAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSelMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDom)
                    .addComponent(lblSeg)
                    .addComponent(lblTer)
                    .addComponent(lblQua)
                    .addComponent(lblQui)
                    .addComponent(lblSex)
                    .addComponent(lblSab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD1)
                    .addComponent(lblD2)
                    .addComponent(lblD3)
                    .addComponent(lblD4)
                    .addComponent(lblD5)
                    .addComponent(lblD6)
                    .addComponent(lblD7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD8)
                    .addComponent(lblD9)
                    .addComponent(lblD10)
                    .addComponent(lblD11)
                    .addComponent(lblD12)
                    .addComponent(lblD13)
                    .addComponent(lblD14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD15)
                    .addComponent(lblD16)
                    .addComponent(lblD17)
                    .addComponent(lblD18)
                    .addComponent(lblD19)
                    .addComponent(lblD20)
                    .addComponent(lblD21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD22)
                    .addComponent(lblD23)
                    .addComponent(lblD24)
                    .addComponent(lblD25)
                    .addComponent(lblD26)
                    .addComponent(lblD27)
                    .addComponent(lblD28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD29)
                    .addComponent(lblD30)
                    .addComponent(lblD31)
                    .addComponent(lblD32)
                    .addComponent(lblD33)
                    .addComponent(lblD34)
                    .addComponent(lblD35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD36)
                    .addComponent(lblD37)
                    .addComponent(lblD38)
                    .addComponent(lblD39)
                    .addComponent(lblD40)
                    .addComponent(lblD41)
                    .addComponent(lblD42)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("2021");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Sexta");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Janeiro");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("2021");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Sexta");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setText("2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Janeiro");

        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(143, 143, 143)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(54, 54, 54))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)))))
                .addContainerGap(345, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        setBounds(0, 0, 1178, 584);
    }// </editor-fold>//GEN-END:initComponents
//Criação do calendario


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Integer> cboSelAno;
    private javax.swing.JComboBox<String> cboSelMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD10;
    private javax.swing.JLabel lblD11;
    private javax.swing.JLabel lblD12;
    private javax.swing.JLabel lblD13;
    private javax.swing.JLabel lblD14;
    private javax.swing.JLabel lblD15;
    private javax.swing.JLabel lblD16;
    private javax.swing.JLabel lblD17;
    private javax.swing.JLabel lblD18;
    private javax.swing.JLabel lblD19;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblD20;
    private javax.swing.JLabel lblD21;
    private javax.swing.JLabel lblD22;
    private javax.swing.JLabel lblD23;
    private javax.swing.JLabel lblD24;
    private javax.swing.JLabel lblD25;
    private javax.swing.JLabel lblD26;
    private javax.swing.JLabel lblD27;
    private javax.swing.JLabel lblD28;
    private javax.swing.JLabel lblD29;
    private javax.swing.JLabel lblD3;
    private javax.swing.JLabel lblD30;
    private javax.swing.JLabel lblD31;
    private javax.swing.JLabel lblD32;
    private javax.swing.JLabel lblD33;
    private javax.swing.JLabel lblD34;
    private javax.swing.JLabel lblD35;
    private javax.swing.JLabel lblD36;
    private javax.swing.JLabel lblD37;
    private javax.swing.JLabel lblD38;
    private javax.swing.JLabel lblD39;
    private javax.swing.JLabel lblD4;
    private javax.swing.JLabel lblD40;
    private javax.swing.JLabel lblD41;
    private javax.swing.JLabel lblD42;
    private javax.swing.JLabel lblD5;
    private javax.swing.JLabel lblD6;
    private javax.swing.JLabel lblD7;
    private javax.swing.JLabel lblD8;
    private javax.swing.JLabel lblD9;
    private javax.swing.JLabel lblDom;
    private javax.swing.JLabel lblQua;
    private javax.swing.JLabel lblQui;
    private javax.swing.JLabel lblSab;
    private javax.swing.JLabel lblSeg;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTer;
    // End of variables declaration//GEN-END:variables
    public void iniciaCalendario() {
        SimpleDateFormat Ano = new SimpleDateFormat("YYYY");
        SimpleDateFormat Mes = new SimpleDateFormat("MM");
        SimpleDateFormat Dia = new SimpleDateFormat("dd");

        anoFixo = Integer.parseInt(Ano.format(new Date()));
        mesFixo = Integer.parseInt(Mes.format(new Date()));
        diaFixo = Integer.parseInt(Dia.format(new Date()));
        //JOptionPane.showMessageDialog(null, DiaFixo + "/" + MesFixo + "/" + AnoFixo);
        int anoMaximo = anoFixo + 50;
        for (int i = 2000; i < anoMaximo; i++) {
            //há possibilidade de utilizar desta forma cbpSelAno.addItem(""+i);, porém alterei o combobox de Strig para Interger
            cboSelAno.addItem(i);
        }
        cboSelAno.setSelectedItem(anoFixo);

        if (mesFixo == 1) {
            cboSelMes.setSelectedIndex(0);
        } else if (mesFixo == 2) {
            cboSelMes.setSelectedIndex(1);
        } else if (mesFixo == 3) {
            cboSelMes.setSelectedIndex(2);
        } else if (mesFixo == 4) {
            cboSelMes.setSelectedIndex(3);
        } else if (mesFixo == 5) {
            cboSelMes.setSelectedIndex(4);
        } else if (mesFixo == 6) {
            cboSelMes.setSelectedIndex(5);
        } else if (mesFixo == 7) {
            cboSelMes.setSelectedIndex(6);
        } else if (mesFixo == 8) {
            cboSelMes.setSelectedIndex(7);
        } else if (mesFixo == 9) {
            cboSelMes.setSelectedIndex(8);
        } else if (mesFixo == 10) {
            cboSelMes.setSelectedIndex(9);
        } else if (mesFixo == 11) {
            cboSelMes.setSelectedIndex(10);
        } else if (mesFixo == 12) {
            cboSelMes.setSelectedIndex(11);
        }
    }
    public void diaCalendario(){
        lblD1.setText("");
        lblD2.setText("");
        lblD3.setText("");
        lblD4.setText("");
        lblD5.setText("");
        lblD6.setText("");
        lblD7.setText("");
        lblD8.setText("");
        lblD9.setText("");
        lblD10.setText("");
        lblD11.setText("");
        lblD12.setText("");
        lblD13.setText("");
        lblD14.setText("");
        lblD15.setText("");
        lblD16.setText("");
        lblD17.setText("");
        lblD18.setText("");
        lblD19.setText("");
        lblD20.setText("");
        lblD21.setText("");
        lblD22.setText("");
        lblD23.setText("");
        lblD24.setText("");
        lblD25.setText("");
        lblD26.setText("");
        lblD27.setText("");
        lblD28.setText("");
        lblD29.setText("");
        lblD30.setText("");
        lblD31.setText("");
        lblD32.setText("");
        lblD33.setText("");
        lblD34.setText("");
        lblD35.setText("");
        lblD36.setText("");
        lblD37.setText("");
        lblD38.setText("");
        lblD39.setText("");
        lblD40.setText("");
        lblD41.setText("");
        lblD42.setText("");
        
        diaAltera = diaFixo;
        mesAltera = cboSelMes.getSelectedIndex();
        anoAltera = Integer.parseInt(cboSelAno.getSelectedItem().toString());
        
        int totalDiaMes = 0;
        if(mesAltera == 0){
            totalDiaMes = 31;
        }else if (mesAltera == 1){
            int resultado = (anoAltera % 4);
            if(resultado == 0){
                totalDiaMes = 29; //ano é bissesto
            }else{
                totalDiaMes = 28; //ano não é bissesto
            }
        }else if (mesAltera == 2){
            totalDiaMes = 31;
        }else if (mesAltera == 3){
            totalDiaMes = 30;
        }else if (mesAltera == 4){
            totalDiaMes = 31;
        }else if (mesAltera == 5){
            totalDiaMes = 30;
        }else if (mesAltera == 6){
            totalDiaMes = 31;
        }else if (mesAltera == 7){
            totalDiaMes = 30;
        }else if (mesAltera == 8){
            totalDiaMes = 31;
        }else if (mesAltera == 9){
            totalDiaMes = 30;
        }else if (mesAltera == 10){
            totalDiaMes = 31;
        }else if (mesAltera == 11){
            totalDiaMes = 30;}
        else if (mesAltera == 12){
            totalDiaMes = 31;
        }
        Calendar calendar = Calendar.getInstance();
        calendar.set(anoAltera,mesAltera,1);
        int setaDia = 0;
        
        int semana = calendar.get(Calendar.DAY_OF_WEEK);
        if(semana == Calendar.SUNDAY){
            setaDia = 1;//System.out.println("Dom");
        }else if(semana == Calendar.MONDAY){
            setaDia = 2;//System.out.println("Seg");
        }else if(semana == Calendar.TUESDAY){
            setaDia = 3;//System.out.println("Ter");
        }else if(semana == Calendar.WEDNESDAY){
            setaDia = 4;//System.out.println("Qua");
        }else if(semana == Calendar.THURSDAY){
            setaDia = 5;//System.out.println("Qui");
        }else if(semana == Calendar.FRIDAY){
            setaDia = 6;//System.out.println("Sex");
        }else if(semana == Calendar.SATURDAY){
            setaDia = 7;//System.out.println("Sab");
        }
        
        for (int i = 1; i <= totalDiaMes; i++){
            
            switch (setaDia){
                case 1:
                    lblD1.setText(""+i);
                    break;
                case 2:
                    lblD2.setText(""+i);                    
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD2.setForeground(Color.RED);
                    }else{
                        lblD2.setForeground(Color.BLACK);
                    }
                    break;
                case 3:
                    lblD3.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD3.setForeground(Color.RED);
                    }else{
                        lblD3.setForeground(Color.BLACK);
                    }
                    break;
                case 4:
                    lblD4.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD4.setForeground(Color.RED);
                    }else{
                        lblD4.setForeground(Color.BLACK);
                    }
                    break; 
                case 5:
                    lblD5.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD5.setForeground(Color.RED);
                    }else{
                        lblD5.setForeground(Color.BLACK);
                    }
                    break; 
                case 6:
                    lblD6.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD6.setForeground(Color.RED);
                    }else{
                        lblD6.setForeground(Color.BLACK);
                    }
                    break;
                case 7:
                    lblD7.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD7.setForeground(Color.RED);
                    }else{
                        lblD7.setForeground(Color.BLACK);
                    }
                    break; 
                case 8:
                    lblD8.setText(""+i);
                    break; 
                case 9:
                    lblD9.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD9.setForeground(Color.RED);
                    }else{
                        lblD9.setForeground(Color.BLACK);
                    }
                    break; 
                case 10:
                    lblD10.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD10.setForeground(Color.RED);
                    }else{
                        lblD10.setForeground(Color.BLACK);
                    }
                    break; 
                case 11:
                    lblD11.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD11.setForeground(Color.RED);
                    }else{
                        lblD11.setForeground(Color.BLACK);
                    }
                    break; 
                case 12:
                    lblD12.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD12.setForeground(Color.RED);
                    }else{
                        lblD12.setForeground(Color.BLACK);
                    }
                    break; 
                case 13:
                    lblD13.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD13.setForeground(Color.RED);
                    }else{
                        lblD13.setForeground(Color.BLACK);
                    }
                    break; 
                case 14:
                    lblD14.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD14.setForeground(Color.RED);
                    }else{
                        lblD14.setForeground(Color.BLACK);
                    }
                    break;
                case 15:
                    lblD15.setText(""+i);
                    break;
                case 16:
                    lblD16.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD16.setForeground(Color.RED);
                    }else{
                        lblD16.setForeground(Color.BLACK);
                    }
                    break; 
                case 17:
                    lblD17.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD17.setForeground(Color.RED);
                    }else{
                        lblD17.setForeground(Color.BLACK);
                    }
                    break; 
                case 18:
                    lblD18.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD18.setForeground(Color.RED);
                    }else{
                        lblD18.setForeground(Color.BLACK);
                    }
                    break;
                case 19:
                    lblD19.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD19.setForeground(Color.RED);
                    }else{
                        lblD19.setForeground(Color.BLACK);
                    }
                    break; 
                case 20:
                    lblD20.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD20.setForeground(Color.RED);
                    }else{
                        lblD20.setForeground(Color.BLACK);
                    }
                    break; 
                case 21:
                    lblD21.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD21.setForeground(Color.RED);
                    }else{
                        lblD21.setForeground(Color.BLACK);
                    }
                    break; 
                case 22:
                    lblD22.setText(""+i);
                    break; 
                case 23:
                    lblD23.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD23.setForeground(Color.RED);
                    }else{
                        lblD23.setForeground(Color.BLACK);
                    }
                    break; 
                case 24:
                    lblD24.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD24.setForeground(Color.RED);
                    }else{
                        lblD24.setForeground(Color.BLACK);
                    }
                    break; 
                case 25:
                    lblD25.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD25.setForeground(Color.RED);
                    }else{
                        lblD25.setForeground(Color.BLACK);
                    }
                    break; 
                case 26:
                    lblD26.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD26.setForeground(Color.RED);
                    }else{
                        lblD26.setForeground(Color.BLACK);
                    }
                    break;
                case 27:
                    lblD27.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD27.setForeground(Color.RED);
                    }else{
                        lblD27.setForeground(Color.BLACK);
                    }
                    break;
                case 28:
                    lblD28.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD28.setForeground(Color.RED);
                    }else{
                        lblD28.setForeground(Color.BLACK);
                    }
                    break;
                case 29:
                    lblD29.setText(""+i);
                    break;    
                case 30:
                    lblD30.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD30.setForeground(Color.RED);
                    }else{
                        lblD30.setForeground(Color.BLACK);
                    }
                    break; 
                case 31:
                    lblD31.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD31.setForeground(Color.RED);
                    }else{
                        lblD31.setForeground(Color.BLACK);
                    }
                    break;
                case 32:
                    lblD32.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD32.setForeground(Color.RED);
                    }else{
                        lblD32.setForeground(Color.BLACK);
                    }
                    break; 
                case 33:
                    lblD33.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD33.setForeground(Color.RED);
                    }else{
                        lblD33.setForeground(Color.BLACK);
                    }
                    break; 
                case 34:
                    lblD34.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD34.setForeground(Color.RED);
                    }else{
                        lblD34.setForeground(Color.BLACK);
                    }
                    break;
                case 35:
                    lblD35.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD35.setForeground(Color.RED);
                    }else{
                        lblD35.setForeground(Color.BLACK);
                    }
                    break;    
                case 36:
                    lblD36.setText(""+i);
                    break; 
                case 37:
                    lblD37.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD37.setForeground(Color.RED);
                    }else{
                        lblD37.setForeground(Color.BLACK);
                    }
                    break; 
                case 38:
                    lblD38.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD38.setForeground(Color.RED);
                    }else{
                        lblD38.setForeground(Color.BLACK);
                    }
                    break; 
                case 39:
                    lblD39.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD39.setForeground(Color.RED);
                    }else{
                        lblD39.setForeground(Color.BLACK);
                    }
                    break; 
                case 40:
                    lblD40.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD40.setForeground(Color.RED);
                    }else{
                        lblD40.setForeground(Color.BLACK);
                    }
                    break;
                case 41:
                    lblD41.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD41.setForeground(Color.RED);
                    }else{
                        lblD41.setForeground(Color.BLACK);
                    }
                    break;
                case 42:
                    lblD42.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD42.setForeground(Color.RED);
                    }else{
                        lblD42.setForeground(Color.BLACK);
                    }
                    break; 
            }
            setaDia++;
    }
    }
}
