/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cleanPet.telas;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;

/**
 *
 * @author marcioc
 */
public class TelaAgenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAgenda
     */
    int anoFixo = 0, mesFixo = 0, diaFixo;
    int anoAltera = 0, mesAltera = 0, diaAltera = 0;
    int valorSelecao = 0;

    public TelaAgenda() {
        initComponents();
        iniciaCalendario();
        diaCalendario();
        verificaSemana();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        cboSelAno = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        lblDom = new javax.swing.JLabel();
        lblSeg = new javax.swing.JLabel();
        lblTer = new javax.swing.JLabel();
        lblQua = new javax.swing.JLabel();
        lblQui = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblSab = new javax.swing.JLabel();
        lblD1 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        lblD3 = new javax.swing.JLabel();
        lblD4 = new javax.swing.JLabel();
        lblD5 = new javax.swing.JLabel();
        lblD6 = new javax.swing.JLabel();
        lblD7 = new javax.swing.JLabel();
        lblD8 = new javax.swing.JLabel();
        lblD9 = new javax.swing.JLabel();
        lblD10 = new javax.swing.JLabel();
        lblD11 = new javax.swing.JLabel();
        lblD12 = new javax.swing.JLabel();
        lblD13 = new javax.swing.JLabel();
        lblD14 = new javax.swing.JLabel();
        lblD15 = new javax.swing.JLabel();
        lblD16 = new javax.swing.JLabel();
        lblD17 = new javax.swing.JLabel();
        lblD18 = new javax.swing.JLabel();
        lblD19 = new javax.swing.JLabel();
        lblD20 = new javax.swing.JLabel();
        lblD21 = new javax.swing.JLabel();
        lblD22 = new javax.swing.JLabel();
        lblD23 = new javax.swing.JLabel();
        lblD24 = new javax.swing.JLabel();
        lblD25 = new javax.swing.JLabel();
        lblD26 = new javax.swing.JLabel();
        lblD27 = new javax.swing.JLabel();
        lblD28 = new javax.swing.JLabel();
        lblD29 = new javax.swing.JLabel();
        lblD30 = new javax.swing.JLabel();
        lblD31 = new javax.swing.JLabel();
        lblD32 = new javax.swing.JLabel();
        lblD33 = new javax.swing.JLabel();
        lblD34 = new javax.swing.JLabel();
        lblD35 = new javax.swing.JLabel();
        lblD36 = new javax.swing.JLabel();
        lblD37 = new javax.swing.JLabel();
        lblD38 = new javax.swing.JLabel();
        lblD39 = new javax.swing.JLabel();
        lblD40 = new javax.swing.JLabel();
        lblD41 = new javax.swing.JLabel();
        lblD42 = new javax.swing.JLabel();
        cboSelMes = new javax.swing.JComboBox<>();
        lblAnoPag1 = new javax.swing.JLabel();
        lblSemanaPag1 = new javax.swing.JLabel();
        lblDiaPag1 = new javax.swing.JLabel();
        lblMesPag1 = new javax.swing.JLabel();
        lblAnoPag2 = new javax.swing.JLabel();
        lblSemanaPag2 = new javax.swing.JLabel();
        lblDiaPag2 = new javax.swing.JLabel();
        lblMesPag2 = new javax.swing.JLabel();
        btnDataHoje = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agenda");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cboSelAno.setEditable(true);
        cboSelAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSelAnoActionPerformed(evt);
            }
        });

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        lblDom.setForeground(new java.awt.Color(255, 0, 0));
        lblDom.setText("Dom");

        lblSeg.setText("Seg");

        lblTer.setText("Ter");

        lblQua.setText("Qua");

        lblQui.setText("Qui");

        lblSex.setText("Sex");

        lblSab.setText("Sab");

        lblD1.setForeground(new java.awt.Color(255, 0, 0));
        lblD1.setText("0");

        lblD2.setText("0");

        lblD3.setText("0");

        lblD4.setText("0");

        lblD5.setText("0");

        lblD6.setText("0");

        lblD7.setText("0");

        lblD8.setForeground(new java.awt.Color(255, 0, 0));
        lblD8.setText("0");

        lblD9.setText("0");

        lblD10.setText("0");

        lblD11.setText("0");

        lblD12.setText("0");

        lblD13.setText("0");

        lblD14.setText("0");

        lblD15.setForeground(new java.awt.Color(255, 0, 0));
        lblD15.setText("0");

        lblD16.setText("0");

        lblD17.setText("0");

        lblD18.setText("0");

        lblD19.setText("0");

        lblD20.setText("0");

        lblD21.setText("0");

        lblD22.setForeground(new java.awt.Color(255, 0, 0));
        lblD22.setText("0");

        lblD23.setText("0");

        lblD24.setText("0");

        lblD25.setText("0");

        lblD26.setText("0");

        lblD27.setText("0");

        lblD28.setText("0");

        lblD29.setForeground(new java.awt.Color(255, 0, 0));
        lblD29.setText("0");

        lblD30.setText("0");

        lblD31.setText("0");

        lblD32.setText("0");

        lblD33.setText("0");

        lblD34.setText("0");

        lblD35.setText("0");

        lblD36.setForeground(new java.awt.Color(255, 0, 0));
        lblD36.setText("0");

        lblD37.setText("0");

        lblD38.setText("0");

        lblD39.setText("0");

        lblD40.setText("0");

        lblD41.setText("0");

        lblD42.setText("0");

        cboSelMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", " ", " ", " " }));
        cboSelMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSelMesActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(cboSelAno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblDom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblSeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblTer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblQua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblQui, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblSex, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblSab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(cboSelMes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblDom)
                            .addComponent(lblD1)
                            .addComponent(lblD8)
                            .addComponent(lblD15)
                            .addComponent(lblD22)
                            .addComponent(lblD29)
                            .addComponent(lblD36))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSeg)
                            .addComponent(lblD2)
                            .addComponent(lblD9)
                            .addComponent(lblD16)
                            .addComponent(lblD23)
                            .addComponent(lblD30)
                            .addComponent(lblD37))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(lblD3)
                                .addComponent(lblD10)
                                .addComponent(lblD17)
                                .addComponent(lblD24)
                                .addComponent(lblD31)
                                .addComponent(lblD38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(lblTer)
                                .addGap(18, 18, 18)))
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblQua)
                            .addComponent(lblD4)
                            .addComponent(lblD11)
                            .addComponent(lblD18)
                            .addComponent(lblD25)
                            .addComponent(lblD32)
                            .addComponent(lblD39))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblQui)
                            .addComponent(lblD5)
                            .addComponent(lblD12)
                            .addComponent(lblD19)
                            .addComponent(lblD26)
                            .addComponent(lblD33)
                            .addComponent(lblD40))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSex)
                            .addComponent(lblD6)
                            .addComponent(lblD13)
                            .addComponent(lblD20)
                            .addComponent(lblD27)
                            .addComponent(lblD34)
                            .addComponent(lblD41))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSab)
                            .addComponent(lblD7)
                            .addComponent(lblD14)
                            .addComponent(lblD21)
                            .addComponent(lblD28)
                            .addComponent(lblD35)
                            .addComponent(lblD42)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cboSelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(cboSelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboSelMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDom)
                    .addComponent(lblSeg)
                    .addComponent(lblTer)
                    .addComponent(lblQua)
                    .addComponent(lblQui)
                    .addComponent(lblSex)
                    .addComponent(lblSab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD1)
                    .addComponent(lblD2)
                    .addComponent(lblD3)
                    .addComponent(lblD4)
                    .addComponent(lblD5)
                    .addComponent(lblD6)
                    .addComponent(lblD7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD8)
                    .addComponent(lblD9)
                    .addComponent(lblD10)
                    .addComponent(lblD11)
                    .addComponent(lblD12)
                    .addComponent(lblD13)
                    .addComponent(lblD14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD15)
                    .addComponent(lblD16)
                    .addComponent(lblD17)
                    .addComponent(lblD18)
                    .addComponent(lblD19)
                    .addComponent(lblD20)
                    .addComponent(lblD21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD22)
                    .addComponent(lblD23)
                    .addComponent(lblD24)
                    .addComponent(lblD25)
                    .addComponent(lblD26)
                    .addComponent(lblD27)
                    .addComponent(lblD28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD29)
                    .addComponent(lblD30)
                    .addComponent(lblD31)
                    .addComponent(lblD32)
                    .addComponent(lblD33)
                    .addComponent(lblD34)
                    .addComponent(lblD35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD36)
                    .addComponent(lblD37)
                    .addComponent(lblD38)
                    .addComponent(lblD39)
                    .addComponent(lblD40)
                    .addComponent(lblD41)
                    .addComponent(lblD42)))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(cboSelAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        lblAnoPag1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAnoPag1.setText("2020");

        lblSemanaPag1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemanaPag1.setText("Sexta");

        lblDiaPag1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDiaPag1.setText("1");

        lblMesPag1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMesPag1.setText("Janeiro");

        lblAnoPag2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAnoPag2.setText("2020");

        lblSemanaPag2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemanaPag2.setText("Sexta");

        lblDiaPag2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDiaPag2.setText("2");

        lblMesPag2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMesPag2.setText("Janeiro");

        btnDataHoje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cleanPet/icones/DiaAtual.png"))); // NOI18N
        btnDataHoje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataHojeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataHojeMouseExited(evt);
            }
        });
        btnDataHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataHojeActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblAnoPag1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblSemanaPag1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDiaPag1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblMesPag1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblAnoPag2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblSemanaPag2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblDiaPag2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblMesPag2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnDataHoje, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblAnoPag1))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSemanaPag1)
                    .addComponent(lblDiaPag1)
                    .addComponent(lblMesPag1))
                .addGap(143, 143, 143)
                .addComponent(lblAnoPag2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSemanaPag2)
                    .addComponent(lblDiaPag2)
                    .addComponent(lblMesPag2))
                .addGap(54, 54, 54))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblSemanaPag2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaPag2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnoPag2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMesPag2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSemanaPag1)
                                .addGap(47, 47, 47))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaPag1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnoPag1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMesPag1)))
                .addContainerGap(345, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        setBounds(0, 0, 1178, 584);
    }// </editor-fold>//GEN-END:initComponents

    private void cboSelMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSelMesActionPerformed
        // TODO add your handling code here:
        diaAltera = diaFixo;
        diaCalendario();
    }//GEN-LAST:event_cboSelMesActionPerformed

    private void cboSelAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSelAnoActionPerformed
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(cboSelAno.getSelectedItem().toString());
            diaAltera = diaFixo;
            diaCalendario();
            lblAnoPag1.setText(cboSelAno.getSelectedItem().toString());
            lblAnoPag2.setText(cboSelAno.getSelectedItem().toString());
        }catch(Exception e){
            cboSelAno.setSelectedItem(anoFixo);
        }
    }//GEN-LAST:event_cboSelAnoActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        valorSelecao = Integer.parseInt(jSpinner1.getValue().toString());
        int x = cboSelMes.getSelectedIndex();
        int ano = Integer.parseInt(cboSelAno.getSelectedItem().toString());
        
        if(valorSelecao == -1){
            if(cboSelMes.getSelectedIndex() != 11){
               cboSelMes.setSelectedIndex(x + 1); 
            }else{
                cboSelMes.setSelectedIndex(0);
                ano = ano +1;
                cboSelAno.setSelectedItem(ano);
            }
        }
        if(valorSelecao == +1){
            if(cboSelMes.getSelectedIndex() != 0){
               cboSelMes.setSelectedIndex(x - 1); 
            }else{
                cboSelMes.setSelectedIndex(11);
                ano = ano -1;
                cboSelAno.setSelectedItem(ano);
            }
        }
        jSpinner1.setValue(0);
    }//GEN-LAST:event_jSpinner1StateChanged

    private void btnDataHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataHojeActionPerformed
        // TODO add your handling code here:
        iniciaCalendario();
        diaCalendario();
        
        
    }//GEN-LAST:event_btnDataHojeActionPerformed

    private void btnDataHojeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataHojeMouseEntered
        // Coloca borda no btn
        btnDataHoje.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_btnDataHojeMouseEntered

    private void btnDataHojeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataHojeMouseExited
        // Remover a borda do btn
        btnDataHoje.setBorder(null);
    }//GEN-LAST:event_btnDataHojeMouseExited



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataHoje;
    private javax.swing.JComboBox cboSelAno;
    private javax.swing.JComboBox<String> cboSelMes;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblAnoPag1;
    private javax.swing.JLabel lblAnoPag2;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD10;
    private javax.swing.JLabel lblD11;
    private javax.swing.JLabel lblD12;
    private javax.swing.JLabel lblD13;
    private javax.swing.JLabel lblD14;
    private javax.swing.JLabel lblD15;
    private javax.swing.JLabel lblD16;
    private javax.swing.JLabel lblD17;
    private javax.swing.JLabel lblD18;
    private javax.swing.JLabel lblD19;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblD20;
    private javax.swing.JLabel lblD21;
    private javax.swing.JLabel lblD22;
    private javax.swing.JLabel lblD23;
    private javax.swing.JLabel lblD24;
    private javax.swing.JLabel lblD25;
    private javax.swing.JLabel lblD26;
    private javax.swing.JLabel lblD27;
    private javax.swing.JLabel lblD28;
    private javax.swing.JLabel lblD29;
    private javax.swing.JLabel lblD3;
    private javax.swing.JLabel lblD30;
    private javax.swing.JLabel lblD31;
    private javax.swing.JLabel lblD32;
    private javax.swing.JLabel lblD33;
    private javax.swing.JLabel lblD34;
    private javax.swing.JLabel lblD35;
    private javax.swing.JLabel lblD36;
    private javax.swing.JLabel lblD37;
    private javax.swing.JLabel lblD38;
    private javax.swing.JLabel lblD39;
    private javax.swing.JLabel lblD4;
    private javax.swing.JLabel lblD40;
    private javax.swing.JLabel lblD41;
    private javax.swing.JLabel lblD42;
    private javax.swing.JLabel lblD5;
    private javax.swing.JLabel lblD6;
    private javax.swing.JLabel lblD7;
    private javax.swing.JLabel lblD8;
    private javax.swing.JLabel lblD9;
    private javax.swing.JLabel lblDiaPag1;
    private javax.swing.JLabel lblDiaPag2;
    private javax.swing.JLabel lblDom;
    private javax.swing.JLabel lblMesPag1;
    private javax.swing.JLabel lblMesPag2;
    private javax.swing.JLabel lblQua;
    private javax.swing.JLabel lblQui;
    private javax.swing.JLabel lblSab;
    private javax.swing.JLabel lblSeg;
    private javax.swing.JLabel lblSemanaPag1;
    private javax.swing.JLabel lblSemanaPag2;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTer;
    // End of variables declaration//GEN-END:variables
    
    //Criação do calendario
    public void iniciaCalendario() {
        SimpleDateFormat Ano = new SimpleDateFormat("YYYY");
        SimpleDateFormat Mes = new SimpleDateFormat("MM");
        SimpleDateFormat Dia = new SimpleDateFormat("dd");

        anoFixo = Integer.parseInt(Ano.format(new Date()));
        mesFixo = Integer.parseInt(Mes.format(new Date()));
        diaFixo = Integer.parseInt(Dia.format(new Date()));
        //JOptionPane.showMessageDialog(null, DiaFixo + "/" + MesFixo + "/" + AnoFixo);
        int anoMaximo = anoFixo + 50;
        for (int i = 2000; i < anoMaximo; i++) {
            //há possibilidade de utilizar desta forma cbpSelAno.addItem(""+i);, porém alterei o combobox de Strig para Interger
            cboSelAno.addItem(i);
        }
        cboSelAno.setSelectedItem(anoFixo);

        if (mesFixo == 1) {
            cboSelMes.setSelectedIndex(0);
        } else if (mesFixo == 2) {
            cboSelMes.setSelectedIndex(1);
        } else if (mesFixo == 3) {
            cboSelMes.setSelectedIndex(2);
        } else if (mesFixo == 4) {
            cboSelMes.setSelectedIndex(3);
        } else if (mesFixo == 5) {
            cboSelMes.setSelectedIndex(4);
        } else if (mesFixo == 6) {
            cboSelMes.setSelectedIndex(5);
        } else if (mesFixo == 7) {
            cboSelMes.setSelectedIndex(6);
        } else if (mesFixo == 8) {
            cboSelMes.setSelectedIndex(7);
        } else if (mesFixo == 9) {
            cboSelMes.setSelectedIndex(8);
        } else if (mesFixo == 10) {
            cboSelMes.setSelectedIndex(9);
        } else if (mesFixo == 11) {
            cboSelMes.setSelectedIndex(10);
        } else if (mesFixo == 12) {
            cboSelMes.setSelectedIndex(11);
        }
    }
    public void diaCalendario(){
        lblD1.setText("");
        lblD2.setText("");
        lblD3.setText("");
        lblD4.setText("");
        lblD5.setText("");
        lblD6.setText("");
        lblD7.setText("");
        lblD8.setText("");
        lblD9.setText("");
        lblD10.setText("");
        lblD11.setText("");
        lblD12.setText("");
        lblD13.setText("");
        lblD14.setText("");
        lblD15.setText("");
        lblD16.setText("");
        lblD17.setText("");
        lblD18.setText("");
        lblD19.setText("");
        lblD20.setText("");
        lblD21.setText("");
        lblD22.setText("");
        lblD23.setText("");
        lblD24.setText("");
        lblD25.setText("");
        lblD26.setText("");
        lblD27.setText("");
        lblD28.setText("");
        lblD29.setText("");
        lblD30.setText("");
        lblD31.setText("");
        lblD32.setText("");
        lblD33.setText("");
        lblD34.setText("");
        lblD35.setText("");
        lblD36.setText("");
        lblD37.setText("");
        lblD38.setText("");
        lblD39.setText("");
        lblD40.setText("");
        lblD41.setText("");
        lblD42.setText("");
        
        diaAltera = diaFixo;
        mesAltera = cboSelMes.getSelectedIndex();
        anoAltera = Integer.parseInt(cboSelAno.getSelectedItem().toString());
        
        int totalDiaMes = 0;
        if(mesAltera == 0){
            totalDiaMes = 31;
        }else if (mesAltera == 1){
            int resultado = (anoAltera % 4);
            if(resultado == 0){
                totalDiaMes = 29; //ano é bissesto
            }else{
                totalDiaMes = 28; //ano não é bissesto
            }
        }else if (mesAltera == 2){
            totalDiaMes = 31;
        }else if (mesAltera == 3){
            totalDiaMes = 30;
        }else if (mesAltera == 4){
            totalDiaMes = 31;
        }else if (mesAltera == 5){
            totalDiaMes = 30;
        }else if (mesAltera == 6){
            totalDiaMes = 31;
        }else if (mesAltera == 7){
            totalDiaMes = 30;
        }else if (mesAltera == 8){
            totalDiaMes = 31;
        }else if (mesAltera == 9){
            totalDiaMes = 30;
        }else if (mesAltera == 10){
            totalDiaMes = 31;
        }else if (mesAltera == 11){
            totalDiaMes = 30;}
        else if (mesAltera == 12){
            totalDiaMes = 31;
        }
        Calendar calendar = Calendar.getInstance();
        calendar.set(anoAltera,mesAltera,1);
        int setaDia = 0;
        
        int semana = calendar.get(Calendar.DAY_OF_WEEK);
        if(semana == Calendar.SUNDAY){
            setaDia = 1;//System.out.println("Dom");
        }else if(semana == Calendar.MONDAY){
            setaDia = 2;//System.out.println("Seg");
        }else if(semana == Calendar.TUESDAY){
            setaDia = 3;//System.out.println("Ter");
        }else if(semana == Calendar.WEDNESDAY){
            setaDia = 4;//System.out.println("Qua");
        }else if(semana == Calendar.THURSDAY){
            setaDia = 5;//System.out.println("Qui");
        }else if(semana == Calendar.FRIDAY){
            setaDia = 6;//System.out.println("Sex");
        }else if(semana == Calendar.SATURDAY){
            setaDia = 7;//System.out.println("Sab");
        }
        
        for (int i = 1; i <= totalDiaMes; i++){
            
            switch (setaDia){
                case 1:
                    lblD1.setText(""+i);
                    break;
                case 2:
                    lblD2.setText(""+i);                    
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD2.setForeground(Color.RED);
                    }else{
                        lblD2.setForeground(Color.BLACK);
                    }
                    break;
                case 3:
                    lblD3.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD3.setForeground(Color.RED);
                    }else{
                        lblD3.setForeground(Color.BLACK);
                    }
                    break;
                case 4:
                    lblD4.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD4.setForeground(Color.RED);
                    }else{
                        lblD4.setForeground(Color.BLACK);
                    }
                    break; 
                case 5:
                    lblD5.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD5.setForeground(Color.RED);
                    }else{
                        lblD5.setForeground(Color.BLACK);
                    }
                    break; 
                case 6:
                    lblD6.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD6.setForeground(Color.RED);
                    }else{
                        lblD6.setForeground(Color.BLACK);
                    }
                    break;
                case 7:
                    lblD7.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD7.setForeground(Color.RED);
                    }else{
                        lblD7.setForeground(Color.BLACK);
                    }
                    break; 
                case 8:
                    lblD8.setText(""+i);
                    break; 
                case 9:
                    lblD9.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD9.setForeground(Color.RED);
                    }else{
                        lblD9.setForeground(Color.BLACK);
                    }
                    break; 
                case 10:
                    lblD10.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD10.setForeground(Color.RED);
                    }else{
                        lblD10.setForeground(Color.BLACK);
                    }
                    break; 
                case 11:
                    lblD11.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD11.setForeground(Color.RED);
                    }else{
                        lblD11.setForeground(Color.BLACK);
                    }
                    break; 
                case 12:
                    lblD12.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD12.setForeground(Color.RED);
                    }else{
                        lblD12.setForeground(Color.BLACK);
                    }
                    break; 
                case 13:
                    lblD13.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD13.setForeground(Color.RED);
                    }else{
                        lblD13.setForeground(Color.BLACK);
                    }
                    break; 
                case 14:
                    lblD14.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD14.setForeground(Color.RED);
                    }else{
                        lblD14.setForeground(Color.BLACK);
                    }
                    break;
                case 15:
                    lblD15.setText(""+i);
                    break;
                case 16:
                    lblD16.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD16.setForeground(Color.RED);
                    }else{
                        lblD16.setForeground(Color.BLACK);
                    }
                    break; 
                case 17:
                    lblD17.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD17.setForeground(Color.RED);
                    }else{
                        lblD17.setForeground(Color.BLACK);
                    }
                    break; 
                case 18:
                    lblD18.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD18.setForeground(Color.RED);
                    }else{
                        lblD18.setForeground(Color.BLACK);
                    }
                    break;
                case 19:
                    lblD19.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD19.setForeground(Color.RED);
                    }else{
                        lblD19.setForeground(Color.BLACK);
                    }
                    break; 
                case 20:
                    lblD20.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD20.setForeground(Color.RED);
                    }else{
                        lblD20.setForeground(Color.BLACK);
                    }
                    break; 
                case 21:
                    lblD21.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD21.setForeground(Color.RED);
                    }else{
                        lblD21.setForeground(Color.BLACK);
                    }
                    break; 
                case 22:
                    lblD22.setText(""+i);
                    break; 
                case 23:
                    lblD23.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD23.setForeground(Color.RED);
                    }else{
                        lblD23.setForeground(Color.BLACK);
                    }
                    break; 
                case 24:
                    lblD24.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD24.setForeground(Color.RED);
                    }else{
                        lblD24.setForeground(Color.BLACK);
                    }
                    break; 
                case 25:
                    lblD25.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD25.setForeground(Color.RED);
                    }else{
                        lblD25.setForeground(Color.BLACK);
                    }
                    break; 
                case 26:
                    lblD26.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD26.setForeground(Color.RED);
                    }else{
                        lblD26.setForeground(Color.BLACK);
                    }
                    break;
                case 27:
                    lblD27.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD27.setForeground(Color.RED);
                    }else{
                        lblD27.setForeground(Color.BLACK);
                    }
                    break;
                case 28:
                    lblD28.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD28.setForeground(Color.RED);
                    }else{
                        lblD28.setForeground(Color.BLACK);
                    }
                    break;
                case 29:
                    lblD29.setText(""+i);
                    break;    
                case 30:
                    lblD30.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD30.setForeground(Color.RED);
                    }else{
                        lblD30.setForeground(Color.BLACK);
                    }
                    break; 
                case 31:
                    lblD31.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD31.setForeground(Color.RED);
                    }else{
                        lblD31.setForeground(Color.BLACK);
                    }
                    break;
                case 32:
                    lblD32.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD32.setForeground(Color.RED);
                    }else{
                        lblD32.setForeground(Color.BLACK);
                    }
                    break; 
                case 33:
                    lblD33.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD33.setForeground(Color.RED);
                    }else{
                        lblD33.setForeground(Color.BLACK);
                    }
                    break; 
                case 34:
                    lblD34.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD34.setForeground(Color.RED);
                    }else{
                        lblD34.setForeground(Color.BLACK);
                    }
                    break;
                case 35:
                    lblD35.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD35.setForeground(Color.RED);
                    }else{
                        lblD35.setForeground(Color.BLACK);
                    }
                    break;    
                case 36:
                    lblD36.setText(""+i);
                    break; 
                case 37:
                    lblD37.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD37.setForeground(Color.RED);
                    }else{
                        lblD37.setForeground(Color.BLACK);
                    }
                    break; 
                case 38:
                    lblD38.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD38.setForeground(Color.RED);
                    }else{
                        lblD38.setForeground(Color.BLACK);
                    }
                    break; 
                case 39:
                    lblD39.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD39.setForeground(Color.RED);
                    }else{
                        lblD39.setForeground(Color.BLACK);
                    }
                    break; 
                case 40:
                    lblD40.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD40.setForeground(Color.RED);
                    }else{
                        lblD40.setForeground(Color.BLACK);
                    }
                    break;
                case 41:
                    lblD41.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD41.setForeground(Color.RED);
                    }else{
                        lblD41.setForeground(Color.BLACK);
                    }
                    break;
                case 42:
                    lblD42.setText(""+i);
                    if (i == diaFixo & mesAltera == mesFixo - 1 & anoAltera == anoFixo ){
                        lblD42.setForeground(Color.RED);
                    }else{
                        lblD42.setForeground(Color.BLACK);
                    }
                    break; 
            }
            setaDia++;
        }
        
    }
    public void verificaSemana(){
            try {
              mesAltera = cboSelMes.getSelectedIndex();
              anoAltera = Integer.parseInt(cboSelAno.getSelectedItem().toString());
              Calendar calendarN = Calendar.getInstance();
              calendarN.set(anoAltera,mesAltera,diaAltera);
              
              lblMesPag1.setText(cboSelMes.getSelectedItem().toString());
              lblMesPag2.setText(cboSelMes.getSelectedItem().toString());
              
              lblDiaPag1.setText(""+diaAltera);
              lblDiaPag2.setText(""+diaAltera);
              
              int semanaN = calendarN.get(Calendar.DAY_OF_WEEK);
              if(semanaN == Calendar.SUNDAY){
                  lblSemanaPag1.setText("Domingo");
                  lblSemanaPag2.setText("Domingo");
              }else if(semanaN == Calendar.MONDAY){
                  lblSemanaPag1.setText("Segunda");
                  lblSemanaPag2.setText("Segunda");
              }else if(semanaN == Calendar.TUESDAY){
                  lblSemanaPag1.setText("Terça");
                  lblSemanaPag2.setText("Terça");
              }else if(semanaN == Calendar.WEDNESDAY){
                  lblSemanaPag1.setText("Quarta");
                  lblSemanaPag2.setText("Quarta");
              }else if(semanaN == Calendar.THURSDAY){
                  lblSemanaPag1.setText("Quinta");
                  lblSemanaPag2.setText("Quinta");
              }
            } catch (Exception e) {
            }
        }
}
