/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cleanPet.telas;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author marcioc
 */
public class TelaAgenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAgenda
     */
    int AnoFixo = 0, MesFixo = 0, DiaFixo;
    int AnoAltera = 0, MesAltera = 0, DiaAltera = 0;
    int valorSelecao = 0;
    
    public TelaAgenda() {
        initComponents();
        iniciaCalendario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        cboSelAno = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        lblDom = new javax.swing.JLabel();
        lblSeg = new javax.swing.JLabel();
        lblTer = new javax.swing.JLabel();
        lblQua = new javax.swing.JLabel();
        lblQui = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblSab = new javax.swing.JLabel();
        lblD1 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        lblD3 = new javax.swing.JLabel();
        lblD4 = new javax.swing.JLabel();
        lblD5 = new javax.swing.JLabel();
        lblD6 = new javax.swing.JLabel();
        lblD7 = new javax.swing.JLabel();
        lblD8 = new javax.swing.JLabel();
        lblD9 = new javax.swing.JLabel();
        lblD10 = new javax.swing.JLabel();
        lblD11 = new javax.swing.JLabel();
        lblD12 = new javax.swing.JLabel();
        lblD13 = new javax.swing.JLabel();
        lblD14 = new javax.swing.JLabel();
        lblD15 = new javax.swing.JLabel();
        lblD16 = new javax.swing.JLabel();
        lblD17 = new javax.swing.JLabel();
        lblD18 = new javax.swing.JLabel();
        lblD19 = new javax.swing.JLabel();
        lblD20 = new javax.swing.JLabel();
        lblD21 = new javax.swing.JLabel();
        lblD22 = new javax.swing.JLabel();
        lblD23 = new javax.swing.JLabel();
        lblD24 = new javax.swing.JLabel();
        lblD25 = new javax.swing.JLabel();
        lblD26 = new javax.swing.JLabel();
        lblD27 = new javax.swing.JLabel();
        lblD28 = new javax.swing.JLabel();
        lblD29 = new javax.swing.JLabel();
        lblD30 = new javax.swing.JLabel();
        lblD31 = new javax.swing.JLabel();
        lblD32 = new javax.swing.JLabel();
        lblD33 = new javax.swing.JLabel();
        lblD34 = new javax.swing.JLabel();
        lblD35 = new javax.swing.JLabel();
        lblD36 = new javax.swing.JLabel();
        lblD37 = new javax.swing.JLabel();
        lblD38 = new javax.swing.JLabel();
        lblD39 = new javax.swing.JLabel();
        lblD40 = new javax.swing.JLabel();
        lblD41 = new javax.swing.JLabel();
        lblD42 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agenda");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cboSelAno.setEditable(true);

        lblDom.setText("Dom");

        lblSeg.setText("Seg");

        lblTer.setText("Ter");

        lblQua.setText("Qua");

        lblQui.setText("Qui");

        lblSex.setText("Sex");

        lblSab.setText("Sab");

        lblD1.setText("0");

        lblD2.setText("0");

        lblD3.setText("0");

        lblD4.setText("0");

        lblD5.setText("0");

        lblD6.setText("0");

        lblD7.setText("0");

        lblD8.setText("0");

        lblD9.setText("0");

        lblD10.setText("0");

        lblD11.setText("0");

        lblD12.setText("0");

        lblD13.setText("0");

        lblD14.setText("0");

        lblD15.setText("0");

        lblD16.setText("0");

        lblD17.setText("0");

        lblD18.setText("0");

        lblD19.setText("0");

        lblD20.setText("0");

        lblD21.setText("0");

        lblD22.setText("0");

        lblD23.setText("0");

        lblD24.setText("0");

        lblD25.setText("0");

        lblD26.setText("0");

        lblD27.setText("0");

        lblD28.setText("0");

        lblD29.setText("0");

        lblD30.setText("0");

        lblD31.setText("0");

        lblD32.setText("0");

        lblD33.setText("0");

        lblD34.setText("0");

        lblD35.setText("0");

        lblD36.setText("0");

        lblD37.setText("0");

        lblD38.setText("0");

        lblD39.setText("0");

        lblD40.setText("0");

        lblD41.setText("0");

        lblD42.setText("0");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLayeredPane2.setLayer(cboSelAno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblDom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblSeg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblTer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblQua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblQui, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblSex, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblSab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblD42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblDom)
                            .addComponent(lblD1)
                            .addComponent(lblD8)
                            .addComponent(lblD15)
                            .addComponent(lblD22)
                            .addComponent(lblD29)
                            .addComponent(lblD36))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSeg)
                            .addComponent(lblD2)
                            .addComponent(lblD9)
                            .addComponent(lblD16)
                            .addComponent(lblD23)
                            .addComponent(lblD30)
                            .addComponent(lblD37))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(lblD3)
                                .addComponent(lblD10)
                                .addComponent(lblD17)
                                .addComponent(lblD24)
                                .addComponent(lblD31)
                                .addComponent(lblD38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(lblTer)
                                .addGap(18, 18, 18)))
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblQua)
                            .addComponent(lblD4)
                            .addComponent(lblD11)
                            .addComponent(lblD18)
                            .addComponent(lblD25)
                            .addComponent(lblD32)
                            .addComponent(lblD39))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblQui)
                            .addComponent(lblD5)
                            .addComponent(lblD12)
                            .addComponent(lblD19)
                            .addComponent(lblD26)
                            .addComponent(lblD33)
                            .addComponent(lblD40))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSex)
                            .addComponent(lblD6)
                            .addComponent(lblD13)
                            .addComponent(lblD20)
                            .addComponent(lblD27)
                            .addComponent(lblD34)
                            .addComponent(lblD41))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSab)
                            .addComponent(lblD7)
                            .addComponent(lblD14)
                            .addComponent(lblD21)
                            .addComponent(lblD28)
                            .addComponent(lblD35)
                            .addComponent(lblD42)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cboSelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSelAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDom)
                    .addComponent(lblSeg)
                    .addComponent(lblTer)
                    .addComponent(lblQua)
                    .addComponent(lblQui)
                    .addComponent(lblSex)
                    .addComponent(lblSab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD1)
                    .addComponent(lblD2)
                    .addComponent(lblD3)
                    .addComponent(lblD4)
                    .addComponent(lblD5)
                    .addComponent(lblD6)
                    .addComponent(lblD7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD8)
                    .addComponent(lblD9)
                    .addComponent(lblD10)
                    .addComponent(lblD11)
                    .addComponent(lblD12)
                    .addComponent(lblD13)
                    .addComponent(lblD14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD15)
                    .addComponent(lblD16)
                    .addComponent(lblD17)
                    .addComponent(lblD18)
                    .addComponent(lblD19)
                    .addComponent(lblD20)
                    .addComponent(lblD21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD22)
                    .addComponent(lblD23)
                    .addComponent(lblD24)
                    .addComponent(lblD25)
                    .addComponent(lblD26)
                    .addComponent(lblD27)
                    .addComponent(lblD28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD29)
                    .addComponent(lblD30)
                    .addComponent(lblD31)
                    .addComponent(lblD32)
                    .addComponent(lblD33)
                    .addComponent(lblD34)
                    .addComponent(lblD35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD36)
                    .addComponent(lblD37)
                    .addComponent(lblD38)
                    .addComponent(lblD39)
                    .addComponent(lblD40)
                    .addComponent(lblD41)
                    .addComponent(lblD42)))
        );

        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        setBounds(0, 0, 786, 518);
    }// </editor-fold>//GEN-END:initComponents

    public void iniciaCalendario(){
        SimpleDateFormat Ano = new SimpleDateFormat("YYYY");
        SimpleDateFormat Mes = new SimpleDateFormat("MM");
        SimpleDateFormat Dia = new SimpleDateFormat("dd");
        
        AnoFixo = Integer.parseInt(Ano.format(new Date()));
        MesFixo = Integer.parseInt(Mes.format(new Date()));
        DiaFixo = Integer.parseInt(Dia.format(new Date()));
//        JOptionPane.showMessageDialog(null, DiaFixo+"/"+MesFixo+"/"+AnoFixo);
        int AnoMaximo = AnoFixo + 50;
        for (int i = 2000;i < AnoMaximo;i++){
            cboSelAno.addItem(i);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboSelAno;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD10;
    private javax.swing.JLabel lblD11;
    private javax.swing.JLabel lblD12;
    private javax.swing.JLabel lblD13;
    private javax.swing.JLabel lblD14;
    private javax.swing.JLabel lblD15;
    private javax.swing.JLabel lblD16;
    private javax.swing.JLabel lblD17;
    private javax.swing.JLabel lblD18;
    private javax.swing.JLabel lblD19;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblD20;
    private javax.swing.JLabel lblD21;
    private javax.swing.JLabel lblD22;
    private javax.swing.JLabel lblD23;
    private javax.swing.JLabel lblD24;
    private javax.swing.JLabel lblD25;
    private javax.swing.JLabel lblD26;
    private javax.swing.JLabel lblD27;
    private javax.swing.JLabel lblD28;
    private javax.swing.JLabel lblD29;
    private javax.swing.JLabel lblD3;
    private javax.swing.JLabel lblD30;
    private javax.swing.JLabel lblD31;
    private javax.swing.JLabel lblD32;
    private javax.swing.JLabel lblD33;
    private javax.swing.JLabel lblD34;
    private javax.swing.JLabel lblD35;
    private javax.swing.JLabel lblD36;
    private javax.swing.JLabel lblD37;
    private javax.swing.JLabel lblD38;
    private javax.swing.JLabel lblD39;
    private javax.swing.JLabel lblD4;
    private javax.swing.JLabel lblD40;
    private javax.swing.JLabel lblD41;
    private javax.swing.JLabel lblD42;
    private javax.swing.JLabel lblD5;
    private javax.swing.JLabel lblD6;
    private javax.swing.JLabel lblD7;
    private javax.swing.JLabel lblD8;
    private javax.swing.JLabel lblD9;
    private javax.swing.JLabel lblDom;
    private javax.swing.JLabel lblQua;
    private javax.swing.JLabel lblQui;
    private javax.swing.JLabel lblSab;
    private javax.swing.JLabel lblSeg;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTer;
    // End of variables declaration//GEN-END:variables
}
